version: 2
updates:
  # 1. Node.js / npm (Production Code)
  - package-ecosystem: "npm"
    directory: "/" # root directory with package.json
    schedule:
      interval: "weekly"  # Options: daily, weekly, monthly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
